image: "python:3.7.2"

stages:
  - test_model
  - test_api
  - upload_model
  - deploy_to_heroku

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install virtualenv
  - virtualenv venv
  - . venv/bin/activate

test_inscharge_model:
  stage: test_model
  script:
    - echo "Testing Insurance Charge Model"
    - pip install -r packages/inscharge_model/requirements.txt
    - PYTHONPATH=./packages/inscharge_model python3 packages/inscharge_model/inscharge_model/train_pipeline.py
    - pytest -v packages/inscharge_model/tests

test_api:
  stage: test_api
  script:
    - echo "Test API"
    - pip install -r packages/ml_api/requirements.txt
    - pytest -v packages/ml_api/tests

upload_inscharge_model:
  stage: upload_model
  script:
    - echo "Train, Test and Upload Model"
    - pip install -r packages/inscharge_model/requirements.txt
    - PYTHONPATH=./packages/inscharge_model python3 packages/inscharge_model/inscharge_model/train_pipeline.py
    - chmod +x ./packages/scripts/publish_model.sh
    - ./packages/scripts/publish_model.sh ./packages/inscharge_model/